/*
 * audio_library.h
 *
 *  Created on: Mar 9, 2025
 *  Author: Joseph Fortino
 */

#ifndef INC_AUDIO_LIBRARY_H_
#define INC_AUDIO_LIBRARY_H_


#define NUM_FILES 38
#define MAX_FILENAME_LENGTH 10

extern const char AUDIO_FILENAMES[NUM_FILES][MAX_FILENAME_LENGTH];

typedef enum
{
	ZERO_AUDIO,
	ONE_AUDIO,
	TWO_AUDIO,
	THREE_AUDIO,
	FOUR_AUDIO,
	FIVE_AUDIO,
	SIX_AUDIO,
	SEVEN_AUDIO,
	EIGHT_AUDIO,
	NINE_AUDIO,
	TEN_AUDIO,
	ELEVEN_AUDIO,
	TWELVE_AUDIO,
	THIRTEEN_AUDIO,
	FOURTEEN_AUDIO,
	FIFTEEN_AUDIO,
	SIXTEEN_AUDIO,
	SEVENTEEN_AUDIO,
	EIGHTEEN_AUDIO,
	NINETEEN_AUDIO,
	TWENTY_AUDIO,
	THIRTY_AUDIO,
	FORTY_AUDIO,
	FIFTY_AUDIO,
	SIXTY_AUDIO,
	SEVENTY_AUDIO,
	EIGHTY_AUDIO,
	NINETY_AUDIO,
	HUNDRED_AUDIO,
	AM_AUDIO_AUDIO,
	PM_AUDIO,
	BPM_AUDIO,
	PERCENT_AUDIO,
	YOUR_AUDIO,
	IS_AUDIO,
	SET_AUDIO,
	TIME_AUDIO,
	LOW_BATTERY_AUDIO
} EAudioFile;

#endif /* INC_AUDIO_LIBRARY_H_ */

