/*
 * audio_library.h
 *
 *  Created on: Mar 9, 2025
 *  Author: Joseph Fortino
 */

#ifndef INC_AUDIO_LIBRARY_H_
#define INC_AUDIO_LIBRARY_H_


#define NUM_FILES 72
#define MAX_FILENAME_LENGTH 8

extern const char AUDIO_FILENAMES[NUM_FILES][MAX_FILENAME_LENGTH];

typedef enum
{
	ZERO_AUDIO,
	ONE_AUDIO,
	TWO_AUDIO,
	THREE_AUDIO,
	FOUR_AUDIO,
	FIVE_AUDIO,
	SIX_AUDIO,
	SEVEN_AUDIO,
	EIGHT_AUDIO,
	NINE_AUDIO,
	TEN_AUDIO,
	ELEVEN_AUDIO,
	TWELVE_AUDIO,
	THIRTEEN_AUDIO,
	FOURTEEN_AUDIO,
	FIFTEEN_AUDIO,
	SIXTEEN_AUDIO,
	SEVENTEEN_AUDIO,
	EIGHTEEN_AUDIO,
	NINETEEN_AUDIO,
	TWENTY_AUDIO,
	THIRTY_AUDIO,
	FORTY_AUDIO,
	FIFTY_AUDIO,
	SIXTY_AUDIO,
	SEVENTY_AUDIO,
	EIGHTY_AUDIO,
	NINETY_AUDIO,
	HUNDRED_AUDIO,
	SUNDAY_AUDIO,
	MONDAY_AUDIO,
	TUESDAY_AUDIO,
	WEDNESDAY_AUDIO,
	THRUSDAY_AUDIO,
	FRIDAY_AUDIO,
	SATURDAY_AUDIO,
	JANUARY_AUDIO,
	FEBRARY_AUDIO,
	MARCH_AUDIO,
	APRIL_AUDIO,
	MAY_AUDIO,
	JUN_AUDIO,
	JULY_AUDIO,
	AUGUST_AUDIO,
	SEPEMBER_AUDIO,
	OCTOBER_AUDIO,
	NOVEMBER_AUDIO,
	DECEMBER_AUDIO,
	DATE_AUDIO,
	DAY_AUDIO,
	MONTH_AUDIO,
	YEAR_AUDIO,
	TIME_AUDIO,
	AM_AUDIO,
	PM_AUDIO,
	MINUTE_AUDIO,
	HOUR_AUDIO,
	VIBRATION_AUDIO,
	LENGTH_AUDIO,
	SHORT_AUDIO,
	MEDIUM_AUDIO,
	LONG_AUDIO,
	HR_AUDIO,
	BPM_AUDIO,
	SPO2_AUDIO,
	PERCENT_AUDIO,
	YOUR_AUDIO,
	IS_AUDIO,
	SET_AUDIO,
	LOW_AUDIO,
	BATTERY_AUDIO,
	FORMAT_AUDIO
} EAudioFile;

#endif /* INC_AUDIO_LIBRARY_H_ */

